defaults: &defaults
  host: localhost:3000
  mail:
    address: smtp.ih.com.br
    port: 25
    authentication: plain
    user_name: atendimento@fonip.com.br
    password: pulapula
    enable_starttls_auto: true
  exception:
    email: ["drianotadao@gmail.com", "rodrigo.pest@gmail.com"]
    subject: "[EXCEPTION]"

development:
  <<: *defaults
    
test:
  <<: *defaults

production:
  <<: *defaults
    
# cucumber:
# <<: *defaults